name: Deploy to EKS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name my-eks-cluster --region us-east-1
    - name: Create namespaces
      run: |
        kubectl create namespace dev || true
        kubectl create namespace staging || true
        kubectl create namespace prod || true
    - name: Deploy to EKS (Dev)
      run: kubectl apply -k overlays/dev --namespace dev
    - name: Deploy to EKS (Staging)
      run: kubectl apply -k overlays/staging --namespace staging
    - name: Deploy to EKS (Prod)
      run: kubectl apply -k overlays/prod --namespace prod